import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ConfigureAmplifyClientSide from "./amplify-cognito-config";
import { UserDetailsProvider } from "./context/UserdetailsProvider";
import ClientLayout from "@/components/ClientLayout";
import { CopilotPopup } from "@copilotkit/react-ui";
import { CopilotKit } from "@copilotkit/react-core";

import "@copilotkit/react-ui/styles.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserDetailsProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
             <CopilotKit runtimeUrl="/api/copilotkit">
          <ConfigureAmplifyClientSide />
          <ClientLayout>
            {children}
          </ClientLayout>
          
      </CopilotKit>
        </body>

      </UserDetailsProvider>
    </html>
  );
}
